apiVersion: v1
kind: Pod
metadata:
  name: secret-keeper
  namespace: secure
spec:
  containers:
  - name: secret-keeper
    image: busybox:stable
    command: ['sh', '-c', 'echo $SECRET_STUFF; sleep 3600']
    env:
    - name: SECRET_STUFF
      valueFrom:
        secretKeyRef:
          name: secret-code
          key: code
