apiVersion: v1
kind: Pod
metadata:
  name: emptydir-volume-test
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox:stable
    command: ['sh', '-c', 'echo "writing to empty dir" > /data/mobile.txt; cat /data/mobile.txt']
    volumeMounts:
    - name: empty-volume-data
      mountPath: /data
  volumes:
  - name: empty-volume-data
    emptyDir: {}
