apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-2
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: /home/habiba/projects/hostpath
    type: Directory
