apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /home/habiba/projects/hostpath
    type: Directory
