apiVersion: v1
kind: Service
metadata:
  name: bluegreen-test-svc
spec:
  selector:
    app: bluegreen-test
    color: blue # if ou want to direct user traffic to green env, just change the label here from blue to green.
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
